id: '6f572acd-7633-40e7-eadf-08dbfa1c9dae'
version: 'v1.1'
name: '001'
description: '001'
configuration:
  id: 'biGENIUS.Implementation.Generator.VaultAndMart.Spark'
  version: '1.2.0'
sourceSystems:
  - id: 'ebd0779a-67bb-4fd9-9573-a23b703d786a'
    name: 'ERP'
    description: ''
  - id: 'a874e18a-42b3-49ec-8a9b-7e0fbbc5c28b'
    name: 'POS'
    description: ''
