views:
  - id: 'd7dbe42c-6f31-40d4-9840-e1740698b96f'
    name: 'Datapipe View 1'
    description: 'Default view for data pipe.'
    type: 'data-pipe'
    default: true
    modelObjects:
      - id: '07b17d5a-e591-45b9-9e48-72a37225e131'
      - id: 'e708af35-355e-4a8e-95c4-c08193dbd8db'
      - id: '92fca201-7206-495d-8e8f-a38303f2549d'
      - id: 'f4949848-4a91-4065-a34b-ed2809559bbb'
  - id: '5eb91625-3f75-4d00-85f6-2945c9d53992'
    name: 'Datamodel View 1'
    description: 'Default view for data model.'
    type: 'data-model'
    default: true
    modelObjects: []
